### PR TITLE
Add team's talks & team's photos

### PR DESCRIPTION
**Pull request by josealicea5**

### CODE REVIEW

**Review by mario-bermonti — CHANGES_REQUESTED** [review]
Need to fix yaml "" syntax for descriptions

**Comment by josealicea5** [comment]
Screenshot 2023-04-19 at 7 20 45 PM
There's some "blue" text that shouldn't be that way. I had to remove the "#" in the IRB number because it appears as a comment, and the text next to it became "blue".

**Comment by mario-bermonti** [comment]
Fix #15 and #30

**Review by mario-bermonti — COMMENTED** [review]
Approved

**Pull request merged**
